### ISSUE TITLE
Cannot read prerender of undefined

### ISSUE THREAD

**Issue by ThomasHambach** [tinusn/ui-router-metatags#1]
In your distribution, there is a small check that needs to be added. I do not have time to fork and recompile though, so hope you got the time to make this quick fix!

https://github.com/tinusn/ui-router-metatags/blob/master/src/ui-router-metatags.ts#L102 needs to have a check whether the variable tags is set. So if tags && tags.prerender.

Thanks for the module! Would be cool if you can make it available via bower http://bower.io/

**Comment by tinusn** [comment]
Thanks for reporting that.

I have added the missing check and added the module to bower (ui-router-metatags)
