### ISSUE TITLE
Description is not rendered

### ISSUE THREAD

**Issue by ZuSe** [tinusn/ui-router-metatags#11]
Hi folks,

i have added ui.router.metatags to my project and configured as described in the readme.
It works perfect for the page title, but the the content is not read out at all.
When I check the generated html on my page the attribute keeps empty.

It looks now like this:
    <meta name="fragment" content="!">
    <meta charset="utf-8">
    <title data-ng-bind="MetaTags.title" class="ng-binding">Startseite - MyApp</title>
    <meta name="description" content="">
    <meta name="keywords" content="">

Configure and runBlocks are both executed.

I am using angular 1.5.3 and ui-router 0.2.18. Are there any known problems?

I am really struggeling with this for hours.

**Comment by tinusn** [comment]
I can't tell you anything unless you provide more information - or event better - code samples.

**Comment by mybriyit** [comment]
Hi,
You have used the tool, prerender.io , you recommend?
I read that if used google penalize My Page , I would appreciate advice.

**Comment by tinusn** [comment]
Yes I have used prerender, and its the simplets one to get running with angular in my opinion.

With regards to google I cannot tell you if the penalize it.
