### ISSUE TITLE
Facebook does not recognize metatags

### ISSUE THREAD

**Issue by fullstackteam** [tinusn/ui-router-metatags#12]
Facebook is not able to read metatags when you share or send someone the link from AngularJS website. 

![image](https://cloud.githubusercontent.com/assets/8632934/14388486/0745ce16-fdb7-11e5-9fe9-912699376715.png)

How can I fix that? 
Thanks

**Comment by tinusn** [comment]
As per the documentation:

> Google updated they crawler to execute javascript, so if you use this component then your pages will be indexed by google. However, other crawlers - search engines or social services like facebook - still need to see the page after being rendered by javascript. Therefor it is still recommended to use a service like prerender.io

**Comment by fullstackteam** [comment]
Thanks
