### ISSUE TITLE
how do i update a meta tag from inside the view?

### ISSUE THREAD

**Issue by RongBranovate** [tinusn/ui-router-metatags#13]
First of all, Awesome job on this library!

I have a page that loads dynamic content based on state parameters that appear in the url.
From that content i want to get a string that will be the page's description metatag.
How would i be able to update/change the existing description using `ui-router-metatags` ?

P.S. i can't pass the string even as a hidden param because someone might use the exact link to get to that content so no parameter to work with...

here is my code for that state:

```javascript 
.state('audio', {
    url: "/audio/:songTitle",
    templateUrl: root + 'templ/audio',
    controller: 'audioController as audio',
    resolve: {
        songTitle: function ($stateParams) {
            return $stateParams.songTitle;
        }
    },
    metaTags: {
        title: function (songTitle) {
            return songTitle;
        },
        //TODO: add dynamic description
        description: 'song desc',
        properties: {
            'og:title': function (songTitle) {
                return songTitle;
            },
            'og:type': 'audio',
            //TODO: add dynamic description
            'og:description': 'song desc',
            'og:image': root + 'images/logo.png'
        }
    }
})

**Comment by tinusn** [comment]
Anything that appears in the resolve param can be used - so in your case I would just resolve the description and then use that. In your code you are injecting the $stateParams into the resolve function for the songTitle, but you can inject any service there and then use that to resolve the description.

**Comment by RongBranovate** [comment]
Where would that service go? where should i write it?

**Comment by RongBranovate** [comment]
I think i get it, write it just like any other service, set the description on the controller and get it in the resolve, am i right?

**Comment by RongBranovate** [comment]
So i made a service (i work on separated files):
```javascript
angular.module('myApp.services').service('SongDescService', function () {
    var songDescription;

    function setDescription(description) {
        var songDescription;
    }

    function getDescription(){
        return songDescription;
    }


    return {
        setDescription: setDescription,
        getDescription: getDescription
    }
});
```
and changed my routing to look like so:

```javascript
.state('audio', {
    url: "/audio/:songTitle",
    templateUrl: root + 'templ/audio',
    controller: 'audioController as audio',
    resolve: {
        songTitle: function ($stateParams) {
            return $stateParams.songTitle;
        },
        songDescription: function (SongDescService) {
            return SongDescService.getDescription();
        }
    },
    metaTags: {
        title: function (songTitle) {
            return songTitle;
        },
        description: function(videoDescription){
            return videoDescription;
         },
        properties: {
            'og:title': function (songTitle) {
                return songTitle;
            },
            'og:type': 'audio',
            'og:description':description: function(videoDescription){
                        return videoDescription;
                    },
            'og:image': root + 'images/logo.png'
        }
    }
})
```
and on my controller i run the `setDescription` method with the value i wanted, but the resolve on the routing happens way before that.... so what am i doing wrong?

**Comment by tinusn** [comment]
The resolve array and the metatags are resolved before the controller is invoked, thus you need to provide all the information before entering the controller.

The dynamic part of this, should simply be that you set the description in the resolve service.
