### ISSUE TITLE
Works fine in dev but production throws "Unknown provider"

### ISSUE THREAD

**Issue by mackelito** [tinusn/ui-router-metatags#15]
So this code works fine when I run it without minify and uglify.

`        metaTags: {
          title: function($stateParams) {
            var title = [];
            if ($stateParams.tag) {
              title.push($stateParams.tag);
            }
            if ($stateParams.brand) {
              title.push($stateParams.brand);
            }
            if ($stateParams.categoryName) {
              title.push($stateParams.categoryName);
            }
            if ($stateParams.menuName) {
              title.push($stateParams.menuName);
            }
            return title.join(' ');
          },
          description: '{{category.seoDescription}}',
          keywords: function(category) {
            var keywords = [];
            if (category && category.tags) {
              angular.forEach(category.tags, function(tag) {
                if (!angular.isUndefined(tag)) {
                  keywords.push(tag.name);
                }
              });
              return keywords.join(', ');
            }
          },
          properties: {
            'og:title': 'Frontpage'
          }
        },`

But when running gulp I get this error.
`error occured when trying to get the value of tag: title Error: [$injector:unpr] Unknown provider: tProvider <- t`

Any ideas on what I´m missing?

**Comment by tinusn** [comment]
That is because of your input params to the functions for title and keywords.

$stateParams is going to be minifed and angular needs to know what it is. See the docs for example here:
`
/* @ngInject */
                    statusCode: function(posts) {
}
`
