### ISSUE TITLE
Compatibilty with UI Router 1.0

### ISSUE THREAD

**Issue by DenisLaboureyras** [tinusn/ui-router-metatags#17]
Hello,

I'm using your framework which is very useful!
But recently I've upgraded UI Router to the version 1  and the metatags don't seem to work anymore.
Do you plan on building a new version ?

Thanks for your answer
Denis

**Comment by DenisLaboureyras** [comment]
And my app is an hybrid app (angular 1+2), maybe that's the reason also :)

**Comment by tinusn** [comment]
I have not tried 1.0 yet, but it seems like the whole resolve part have been rewritten. I do not have the time to look further into this, so I am closing this.
