### ISSUE TITLE
Add default values (like the default title) to meta tags

### ISSUE THREAD

**Issue by gkorland** [tinusn/ui-router-metatags#20]
A way to set default values for the meta tags like description and keywords can provide a default solution for none javascript rendering crawlers.

**Comment by tinusn** [comment]
Actually, the only way (as far as I can see) that you can do that, is by removing any existing tags and then adding new ones. But that would be a problem seeing as you have to set all tags using this plugin.

So unless you can convince me that there is another way, I am going to close this.
(But please, if you do, then add a pull request)
