### ISSUE TITLE
Not working with latest ui-router

### ISSUE THREAD

**Issue by Remco75** [tinusn/ui-router-metatags#23]
In the current version of ui router a lot has changed (1.x) the transition callbacks are completly different, thus breaking the module. 

the $stateChangeStart and more no longer exist.
I could make a pr voor a new version, or fork this and release on Npm?

**Comment by tinusn** [comment]
please do

**Comment by rodrigoyoshida** [comment]
It's not working here either, also tried ngMeta module but none of them seems to be working with ui-router 1.0. Hope someone forks one of those projects and provide a solution.

**Comment by eprevot** [comment]
Did someone find a solution for meta tags with angular-ui-router 1.x ?

**Comment by eduardolagares** [comment]
#27 solve this problem.

**Comment by tinusn** [comment]
merged
