### ISSUE TITLE
Meta tags displaying like variable in page view source

### ISSUE THREAD

**Issue by Mari01032015** [tinusn/ui-router-metatags#25]
Hi, Any one know why angular site meta tags and meta informations displaying the variable in page view source. 

**In my page view source**
<title ng-bind="MetaTags.title">Default title</title>
<meta name="description" content="{{MetaTags.description}}">
<meta name="keywords" content="{{MetaTags.keywords}}">
<meta ng-repeat="(key, value) in MetaTags.properties" property="{{key}}" content="{{value}}" >
<meta name="prerender-status-code" content="{{MetaTags.prerender.statusCode}}">
<meta name="prerender-header" ng-if="MetaTags.prerender.header" content="{{MetaTags.prerender.header}}">

**Comment by rodrigoyoshida** [comment]
I guess that's the correct behavior, you must see the correct title only when using inspect element.

**Comment by tinusn** [comment]
As mentioned, view source shows the source received from the server - as this is angular1, it will show all of you script code as is
