### ISSUE TITLE
Compatibility with angular-ui-router/stateEvents

### ISSUE THREAD

**Issue by ggomesdev** [tinusn/ui-router-metatags#26]
When I add ui-router/stateEvents as a project's dependency, it fires a $stateChangeSuccess event which is listened by ui-router-metatags and calls the method `MetaTags.update(toState.metaTags)`.

The problem is when it tries update meta tags by `$stateChangeSuccess`, the `$state.$current.locals.globals` variable is undefined and throw the error: `error occured when trying to get the value of tag: title TypeError: Cannot read property 'globals' of undefined` in that line code:

```
MetaTags.prototype.getValue = function (tagType, tag) {
   try {
      if (!tag) {
         return null;
      }
      else if (typeof tag === 'number') {
         return tag;
      }
      else if (typeof tag === 'string' && tag.trim().length === 0) {
         return null;
      }
      else if (angular.isFunction(tag) || Array.isArray(tag)) {
         return this.$injector.invoke(tag, this, this.$state.$current.locals.globals);
      }
      else {
         //THIS LINE
         return this.$interpolate(tag)(this.$state.$current.locals.globals);
      }
   }
   catch (err) {
      this.$log.error('error occured when trying to get the value of tag:', tagType, err);
      return null;
   }
 };
```

Any idea of how resolve this?

Dependency lists:
- `"angular": "1.5.8"`
- `"angular-ui-router": "^1.0.6"`
-  `"ui-router-metatags": "^1.0.3"`

**Comment by eduardolagares** [comment]
I started to change this method but when it use this.$injector.invoke and this.$interpolate(tag) i can't do it because the this.$state.$current.locals.globals do not exists anymore. Someone know and can help me how to get the resolves values and inject here?

```
getValue(tagType: string, tag) {
			try {
				if (!tag) {
					return null;
				} else if (typeof tag === 'number') {
					return tag;
				} else if (typeof tag === 'string' && tag.trim().length === 0) {
					return null;
				} else if (angular.isFunction(tag) || Array.isArray(tag)) {
					// Not work
					return this.$injector.invoke(tag, this, this.$state.$current.MetaTags);
				} else {
					// Nowt work
					return this.$interpolate(tag)(this.$state.$current.MetaTags);
				}
			} catch (err) {
				this.$log.error('error occured when trying to get the value of tag:', tagType, err);
				return null;
			}
		}

```

**Comment by eduardolagares** [comment]
#27 solve this problem!

**Comment by tinusn** [comment]
Merged
