### ISSUE TITLE
Google now indexes dynamic content

### ISSUE THREAD

**Issue by mackelito** [tinusn/ui-router-metatags#5]
In the readme file we find "Note that you still need a service like prerender.io to actually make these tags visible to search engines!"..

Take a look at http://searchengineland.com/tested-googlebot-crawls-javascript-heres-learned-220157

**Comment by tinusn** [comment]
That is correct - however this only applies to google, thus I still recommend that you use a render service.

**Comment by mackelito** [comment]
Just thought that the text should change a bit as it is not "needed" ;)
