### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by fetis** [tinusn/ui-router-metatags#6]
Why do you have `property` attribute in installation example?
```
<meta ng-repeat="(key, value) in MetaTags.properties" property="{{key}}" content="{{value}}" >
```

It should be `name` instead of.

**Comment by fetis** [comment]
ah, I got it. You're using properties for OpenGraph tags. I used it for robots meta.

What about if I'll add support to this property?

**Comment by tinusn** [comment]
Looks good - I have merged your pull request.

Oh.. and sorry for the late reply, but I were on vacation last week.

**Comment by fetis** [comment]
> Oh.. and sorry for the late reply, but I were on vacation last week.
@tinusn No problem. Thanks for merge.

Are you planning to release new version soon? Do you need that I prepare some documentation for this feature?
